service: hello

# frameworkversion: ${file(../serverless.base.yaml):frameworkversion}

custom: ${file(../serverless.base.yaml):custom}

provider: ${file(../serverless.base.yaml):provider}

resources: ${file(../serverless.base.yaml):resources}

functions:
  api:
    handler: wsgi_handler.handler
    name: yurucorpusapi-${self:service}-${opt:stage, 'dev'}
    environment:
      stage: ${opt:stage, 'dev'}

plugins: ${file(../serverless.base.yaml):plugins}
