service: morpheme

frameworkVersion: ${file(../serverless.base.yaml):frameworkVersion}

custom: ${file(../serverless.base.yaml):custom}

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  httpApi:
    id:
      'Fn::ImportValue': YuruCorpusApiId
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'
        - Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:PutObjectAcl'
          Resource:
            - "arn:aws:s3:::yuru-corpus-prod"
            - "arn:aws:s3:::yuru-corpus-dev"
            - "arn:aws:s3:::yuru-corpus-test"

resources: ${file(../serverless.base.yaml):resources}

functions:
  api:
    handler: wsgi_handler.handler
    name: YuruCorpusApi-${self:service}-${opt:stage, 'dev'}
    environment:
      STAGE: ${opt:stage, 'dev'}
    tags:
      service: YuruCorpus

plugins: ${file(../serverless.base.yaml):plugins}
