service: search

frameworkVersion: ${file(../serverless.base.yaml):frameworkVersion}

custom: ${file(../serverless.base.yaml):custom}

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  httpApi:
    id:
      'Fn::ImportValue': YuruCorpusApiId
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:Get*'
            - 's3:List*'
          Resource:
            - "arn:aws:s3:::yuru-corpus-prod"
            - "arn:aws:s3:::yuru-corpus-dev"
            - "arn:aws:s3:::yuru-corpus-test"

resources: ${file(../serverless.base.yaml):resources}

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 60
    name: YuruCorpusApi-${self:service}-${opt:stage, 'dev'}
    environment:
      STAGE: ${opt:stage, 'dev'}
    tags:
      service: YuruCorpus

plugins: ${file(../serverless.base.yaml):plugins}
